--<ScriptOptions statementTerminator=";"/>
CREATE TABLE APP.PESSOA (PESSOAID BINGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY	(START WITH 1, INCREMENT BY 1), NOME varchar (16), APELIDO varchar(50), BI varchar(50), TYPE_BI varchar(50));
CREATE TABLE APP.USUARIO (usuario varchar (16) PRIMARY KEY NOT NULL, senha varchar(128) NOT NULL);
CREATE SEQUENCE pessoa_id AS BIGINT START WITH 1;
